### ISSUE TITLE
Midi notes...Stream Deck limitations ?

### ISSUE THREAD

**Issue by Jacquesmk2** [sorskoot/StreamDeck-Midi-plugin#4]
I tested the 1.1 version, and had to install a LoopBe1 driver in order to work...BTW very good job !
In use with Drumsamplers however, it seems hard to launch the same note quickly again in order to create doubles or triples, Rolling effects.. is that a limitation of the StreamDeck ?
I could observe it is not yet possible to launch two different midi notes at the same time.
Again, limitations of the interface or Scripting possibilities ?
Best regards

**Comment by Jacquesmk2** [comment]
Hummm...there's more to it, apparently.
Working with Studio One, it appears that some plugins responds correctly to the StreamDeck midi signals sent, while others not. Usually plugins from Presonus are okay.
Other synth (Nexus, Roli, NI, Korg...) does receive midi signals but doesn't emit any sound.
Tested it with Reaper, same problem.
Very strange, actually.
Are there different types of midi events sent ?
Different types of midi notes ?

**Comment by sorskoot** [comment]
Thank you for the feedback. I think there's too much latency when triggering the events. I don't think the stream deck is useful in a realtime scenario. There's one a very simple `note on` event sent. I'm not using it with VSTs or DAWs at the moment. I am going to test this as well.

**Comment by Jacquesmk2** [comment]
Hi Timmy.
First of all I'm not sure whether it is possible to program the StreamDeck so it sends a note on as long as a key is pressed (means : pressed key : note on - released key : note off), that way the problems of everlasting notes would easely be solved.
Then, I opened the midi inspector in Studio One, and could observe that a lot of contradictory control changes (controller all notes off - control changes off for every channel -B#7B00 and B#7900) were sent at the same time of the notes on, which could explain why some VSTI's does not emit any sound, priorizing those control changes over notes on msg.
At last, maybe those conflicts cause problems, but there are absolutely no reasons why we could not get a satisfactory use of triggering midi notes with acceptable latency once those problems are adressed.
What do you think ?
Thanks for all

**Comment by Jacquesmk2** [comment]
![Streamdeck midi sent](https://user-images.githubusercontent.com/10093971/68092369-acd39480-fe8a-11e9-86d8-940ab6392214.png)

**Comment by sorskoot** [comment]
I think this has something to do with the library I am using to send the midi events. I open and close a midi connection every time a button is pressed. I assume the library resets everything when the connection is created. I'll test this and see if I can remove the reset events. 

I link the idea of sending a note off message when the button is released. That won't be too hard to implement. I created issue #5 for this.

**Comment by sorskoot** [comment]
Fixed the opening and closing of the midi device as well in release 1.2
